server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcar?createDatabaseIfNotExist=true
    username: root
    password: 1996
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  application:
    name: profile
  security.oauth2.resource.tokern-info-uri: http://localhost:9191/
  client:
    client-id: mobile
    client-secret: pin
